print('======= DESAFIO 22 =======')
nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome. . .')
print('Seu nome em MAIÚSCULA é {}'.format(nome.upper()))
print('Seu nome em MINÚSCULAS é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('1° Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('2° Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
